// Path: scripts/classification/generate_code_classification_artifacts.mjs
// Description: Generate TS/Rust code-classification extension artifacts from a pinned source list.

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import {
  BASELINE_EXTENSIONS,
  EXCLUDE_EXTENSIONS,
  INCLUDE_EXTENSIONS,
} from "./code_extensions_source.mjs";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..", "..");

const tsOutputPath = path.join(
  repoRoot,
  "app",
  "src",
  "shared",
  "config",
  "generated_code_globs.ts"
);
const rustOutputPath = path.join(
  repoRoot,
  "crates",
  "im_agent",
  "src",
  "repos",
  "generated_code_extensions.rs"
);
const tauriRustOutputPath = path.join(
  repoRoot,
  "src-tauri",
  "src",
  "lib",
  "config",
  "generated_code_globs.rs"
);

function normalizeExtension(value) {
  const trimmed = value.trim().toLowerCase();
  if (trimmed.length === 0) return "";
  return trimmed.startsWith(".") ? trimmed : `.${trimmed}`;
}

function buildSortedExtensionList() {
  const set = new Set(
    BASELINE_EXTENSIONS.map(normalizeExtension).filter((value) => value.length > 0)
  );

  for (const extension of INCLUDE_EXTENSIONS) {
    const normalized = normalizeExtension(extension);
    if (normalized.length > 0) {
      set.add(normalized);
    }
  }

  for (const extension of EXCLUDE_EXTENSIONS) {
    const normalized = normalizeExtension(extension);
    if (normalized.length > 0) {
      set.delete(normalized);
    }
  }

  return Array.from(set).sort((a, b) => a.localeCompare(b));
}

function toTsCodeGlobs(extensions) {
  const lines = extensions.map((extension) => `  "**/*${extension}",`);
  return `// Path: app/src/shared/config/generated_code_globs.ts
// Description: Generated default code globs for extension-based classification.
// Generated by: scripts/classification/generate_code_classification_artifacts.mjs

export const GENERATED_CODE_EXTENSION_GLOBS = [
${lines.join("\n")}
] as const;
`;
}

function toRustExtensions(extensions) {
  const lines = extensions.map((extension) => `    "${extension}",`);
  return `// Path: crates/im_agent/src/repos/generated_code_extensions.rs
// Description: Generated extension list for fallback code classification in the Rust agent.
// Generated by: scripts/classification/generate_code_classification_artifacts.mjs

pub const GENERATED_CODE_EXTENSIONS: &[&str] = &[
${lines.join("\n")}
];
`;
}

function toTauriRustCodeGlobs(extensions) {
  const lines = extensions.map((extension) => `    "**/*${extension}",`);
  return `// Path: src-tauri/src/lib/config/generated_code_globs.rs
// Description: Generated default code globs for Rust-side persisted config migration.
// Generated by: scripts/classification/generate_code_classification_artifacts.mjs

pub const GENERATED_CODE_EXTENSION_GLOBS: &[&str] = &[
${lines.join("\n")}
];
`;
}

async function writeOutputs() {
  const extensions = buildSortedExtensionList();
  await mkdir(path.dirname(tsOutputPath), { recursive: true });
  await mkdir(path.dirname(rustOutputPath), { recursive: true });
  await mkdir(path.dirname(tauriRustOutputPath), { recursive: true });
  await writeFile(tsOutputPath, toTsCodeGlobs(extensions), "utf8");
  await writeFile(rustOutputPath, toRustExtensions(extensions), "utf8");
  await writeFile(tauriRustOutputPath, toTauriRustCodeGlobs(extensions), "utf8");
  console.log(
    `Generated ${extensions.length} code extensions -> ${path.relative(
      repoRoot,
      tsOutputPath
    )}, ${path.relative(repoRoot, rustOutputPath)}, ${path.relative(
      repoRoot,
      tauriRustOutputPath
    )}`
  );
}

writeOutputs().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
